server:
  port: ${SPRING_SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

logging:
  level:
    ROOT: ${SPRING_LOGGING_LEVEL_ROOT:INFO}
  newRelic:
    appender:
      enabled: ${NEW_RELIC_APPENDER_ENABLED:true}

spring:
  application:
    name: item-consumer-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:vhost}
    ssl: 
      enabled: ${RABBITMQ_SSL_ENABLED:false}

queues:
  main: ${RABBITMQ_QUEUE_NAME_MAIN:teste}
